trigger:
- master

variables:
  azureSubscription: YourSubscription
  azureContainerRegistryEndPoint: Contoso.azurecr.io

# Agent should be non micorosft
pool:
  vmImage: ubuntu-latest

steps:

- task: DockerCompose@0
  displayName: 'Docker Compose command'
  inputs:
    azureSubscription: '$(azureSubscription)'
    azureContainerRegistry: '$(azureContainerRegistryEndPoint)'
    dockerComposeFile: 'DemoDockerComposeOnAzure/docker-compose.yml'
    dockerComposeCommand: '--no-ansi   build '
    arguments: '--no-ansi   build '


- task: DockerCompose@0
  displayName: 'Push service images command'
  inputs:
    azureSubscription: '$(azureSubscription)'
    azureContainerRegistry: '$(azureContainerRegistryEndPoint)'
    dockerComposeFile: 'DemoDockerComposeOnAzure/docker-compose.yml'
    action: 'Push services'
   
    includeLatestTag: true
